# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: project_data.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12project_data.proto\x12\x0cproject_data\"B\n\x0e\x46oregroundMask\x12\x11\n\tmask_data\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"5\n\x05State\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\n\n\x02vx\x18\x03 \x01(\x02\x12\n\n\x02vy\x18\x04 \x01(\x02\"1\n\x0bStateUpdate\x12\"\n\x05state\x18\x01 \x01(\x0b\x32\x13.project_data.State\"^\n\tDetection\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\r\n\x05label\x18\x06 \x01(\t\">\n\x0f\x44\x65tectionResult\x12+\n\ndetections\x18\x01 \x03(\x0b\x32\x17.project_data.Detection\"D\n\x05Image\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x32`\n\x16VideoProcessingService\x12\x46\n\x0cProcessVideo\x12\x13.project_data.Image\x1a\x1d.project_data.DetectionResult(\x01\x30\x01\x32\\\n\x16ObjectDetectionService\x12\x42\n\x0c\x44\x65tectObject\x12\x13.project_data.Image\x1a\x1d.project_data.DetectionResult2o\n\x1c\x42\x61\x63kgroundSubtractionService\x12O\n\x1a\x41pplyBackgroundSubtraction\x12\x13.project_data.Image\x1a\x1c.project_data.ForegroundMask2^\n\x13KalmanFilterService\x12G\n\x0bUpdateState\x12\x1d.project_data.DetectionResult\x1a\x19.project_data.StateUpdateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FOREGROUNDMASK']._serialized_start=36
  _globals['_FOREGROUNDMASK']._serialized_end=102
  _globals['_STATE']._serialized_start=104
  _globals['_STATE']._serialized_end=157
  _globals['_STATEUPDATE']._serialized_start=159
  _globals['_STATEUPDATE']._serialized_end=208
  _globals['_DETECTION']._serialized_start=210
  _globals['_DETECTION']._serialized_end=304
  _globals['_DETECTIONRESULT']._serialized_start=306
  _globals['_DETECTIONRESULT']._serialized_end=368
  _globals['_IMAGE']._serialized_start=370
  _globals['_IMAGE']._serialized_end=438
  _globals['_VIDEOPROCESSINGSERVICE']._serialized_start=440
  _globals['_VIDEOPROCESSINGSERVICE']._serialized_end=536
  _globals['_OBJECTDETECTIONSERVICE']._serialized_start=538
  _globals['_OBJECTDETECTIONSERVICE']._serialized_end=630
  _globals['_BACKGROUNDSUBTRACTIONSERVICE']._serialized_start=632
  _globals['_BACKGROUNDSUBTRACTIONSERVICE']._serialized_end=743
  _globals['_KALMANFILTERSERVICE']._serialized_start=745
  _globals['_KALMANFILTERSERVICE']._serialized_end=839
# @@protoc_insertion_point(module_scope)
