# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: background_subtraction.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='background_subtraction.proto',
  package='background_subtraction',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x62\x61\x63kground_subtraction.proto\x12\x16\x62\x61\x63kground_subtraction\"B\n\x0e\x46oregroundMask\x12\x11\n\tmask_data\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x62\x06proto3'
)




_FOREGROUNDMASK = _descriptor.Descriptor(
  name='ForegroundMask',
  full_name='background_subtraction.ForegroundMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mask_data', full_name='background_subtraction.ForegroundMask.mask_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='background_subtraction.ForegroundMask.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='background_subtraction.ForegroundMask.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=122,
)

DESCRIPTOR.message_types_by_name['ForegroundMask'] = _FOREGROUNDMASK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ForegroundMask = _reflection.GeneratedProtocolMessageType('ForegroundMask', (_message.Message,), {
  'DESCRIPTOR' : _FOREGROUNDMASK,
  '__module__' : 'background_subtraction_pb2'
  # @@protoc_insertion_point(class_scope:background_subtraction.ForegroundMask)
  })
_sym_db.RegisterMessage(ForegroundMask)


# @@protoc_insertion_point(module_scope)
