# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_tracking.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15object_tracking.proto\x12\tdetection\"\x16\n\x05Image\x12\r\n\x05image\x18\x01 \x01(\x0c\"?\n\x11\x44\x65tectionResponse\x12*\n\x07objects\x18\x01 \x03(\x0b\x32\x19.detection.DetectedObject\"M\n\x0e\x44\x65tectedObject\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05label\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x0c\n\x04\x62\x62ox\x18\x04 \x03(\x02\x32R\n\x0fObjectDetection\x12?\n\rDetectObjects\x12\x10.detection.Image\x1a\x1c.detection.DetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'object_tracking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGE']._serialized_start=36
  _globals['_IMAGE']._serialized_end=58
  _globals['_DETECTIONRESPONSE']._serialized_start=60
  _globals['_DETECTIONRESPONSE']._serialized_end=123
  _globals['_DETECTEDOBJECT']._serialized_start=125
  _globals['_DETECTEDOBJECT']._serialized_end=202
  _globals['_OBJECTDETECTION']._serialized_start=204
  _globals['_OBJECTDETECTION']._serialized_end=286
# @@protoc_insertion_point(module_scope)
