# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_detection.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16object_detection.proto\x12\x0fobjectdetection\"!\n\x10\x44\x65tectionRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"=\n\x11\x44\x65tectionResponse\x12(\n\x07objects\x18\x01 \x03(\x0b\x32\x17.objectdetection.Object\"l\n\x06Object\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05label\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\t\n\x01x\x18\x04 \x01(\x02\x12\t\n\x01y\x18\x05 \x01(\x02\x12\r\n\x05width\x18\x06 \x01(\x02\x12\x0e\n\x06height\x18\x07 \x01(\x02\x32r\n\x16ObjectDetectionService\x12X\n\rDetectObjects\x12!.objectdetection.DetectionRequest\x1a\".objectdetection.DetectionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'object_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DETECTIONREQUEST']._serialized_start=43
  _globals['_DETECTIONREQUEST']._serialized_end=76
  _globals['_DETECTIONRESPONSE']._serialized_start=78
  _globals['_DETECTIONRESPONSE']._serialized_end=139
  _globals['_OBJECT']._serialized_start=141
  _globals['_OBJECT']._serialized_end=249
  _globals['_OBJECTDETECTIONSERVICE']._serialized_start=251
  _globals['_OBJECTDETECTIONSERVICE']._serialized_end=365
# @@protoc_insertion_point(module_scope)
