# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_tracking.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15object_tracking.proto\x12\x0fobjectdetection\"\x1d\n\x0c\x46rameRequest\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\"\x1e\n\rFrameResponse\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x32i\n\x16ObjectDetectionService\x12O\n\x0cProcessFrame\x12\x1d.objectdetection.FrameRequest\x1a\x1e.objectdetection.FrameResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'object_tracking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAMEREQUEST']._serialized_start=42
  _globals['_FRAMEREQUEST']._serialized_end=71
  _globals['_FRAMERESPONSE']._serialized_start=73
  _globals['_FRAMERESPONSE']._serialized_end=103
  _globals['_OBJECTDETECTIONSERVICE']._serialized_start=105
  _globals['_OBJECTDETECTIONSERVICE']._serialized_end=210
# @@protoc_insertion_point(module_scope)
